services:
  database:
    build:
      context: ./ducdv-docker/mysql
      dockerfile: Dockerfile
    container_name: ducdv-nro-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-nro}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: ./ducdv-docker/java-server
      dockerfile: Dockerfile
    container_name: ducdv-nro-game-server
    restart: always
    depends_on:
      - mysql
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${APP_CLIENT_PORT}:${APP_CLIENT_PORT}"
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    env_file:
      - .env
    networks:
      - app_network

  admin-api:
    build:
      context: ./ducdv-docker/admin-api
      dockerfile: Dockerfile
    container_name: ducdv-nro-admin-api
    restart: always
    depends_on:
      - mysql
    environment:
      - .env
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"

  admin-console:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api-server

volumes:
  mysql_data:
    driver: local
  app_network:
    driver: bridge
