services:
  database:
    build:
      context: .
      dockerfile: ./ducdv-docker/mysql/Dockerfile
    container_name: ducdv-nro-mysql-db
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-nro}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: ./ducdv-docker/java-server/Dockerfile
    container_name: ducdv-nro-game-server
    restart: on-failure:5
    depends_on:
      - database
    ports:
      - "${SERVER_PORT:-8088}:${SERVER_PORT:-8088}"
      - "${APP_CLIENT_PORT:-7979}:${APP_CLIENT_PORT:-7979}"
      - "${APP_SERVER_PORT:-14445}:${APP_SERVER_PORT:-14445}"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./logs/java-server:/app/logs/java-server

  admin-api:
    build:
      context: .
      dockerfile: ./ducdv-docker/admin-api/Dockerfile
    container_name: ducdv-nro-admin-api
    restart: on-failure:5
    depends_on:
      - database
    ports:
      - "${API_SERVER_PORT:-8082}:${API_SERVER_PORT:-8082}"
    env_file:
      - .env
    volumes:
      - ./logs/admin-api:/app/logs/admin-api

  admin-console:
    build:
      context: .
      dockerfile: ./ducdv-docker/admin-console/Dockerfile
    container_name: ducdv-nro-admin-console
    restart: on-failure:5
    ports:
      - "8089:80"
    environment:
      NGINX_PORT: 80
      API_HOST: ducdv-nro-admin-api
      API_PORT: ${API_SERVER_PORT:-8082}
    depends_on:
      - admin-api

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
