services:
  database:
    build:
      context: .
      dockerfile: ./ducdv-docker/mysql/Dockerfile
    container_name: ducdv-nro-mysql-db
    #restart: on-failure:5
    restart: no
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-nro}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - logs_data:/logs

  server:
    build:
      context: .
      dockerfile: ./ducdv-docker/java-server/Dockerfile
    container_name: ducdv-nro-game-server
    #restart: on-failure:5
    restart: no
    depends_on:
      - database
    ports:
      - "${SERVER_PORT:-8088}:${SERVER_PORT:-8088}"
      - "${APP_CLIENT_PORT:-7979}:${APP_CLIENT_PORT:-7979}"
      - "${APP_SERVER_PORT:-14445}:${APP_SERVER_PORT:-14445}"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./ducdv-nro-java-server:/app
      - logs_data:/app/logs

  admin-api:
    build:
      context: .
      dockerfile: ./ducdv-docker/admin-api/Dockerfile
    container_name: ducdv-nro-admin-api
    #restart: on-failure:5
    restart: no
    depends_on:
      - database
    ports:
      - "${API_SERVER_PORT:-8082}:${API_SERVER_PORT:-8082}"
    env_file:
      - .env
    volumes:
      - ./ducdv-nro-admin-api:/app
      - logs_data:/app/logs

  admin-console-builder:
    build:
      context: .
      dockerfile: ./ducdv-docker/admin-console-builder/Dockerfile
    container_name: ducdv-nro-admin-console-builder
    restart: no
    volumes:
      - ./ducdv-nro-admin-console:/app
      - ./ducdv-nro-admin-console/dist:/app/dist
    depends_on:
      - admin-api

  admin-console:
    build:
      context: .
      dockerfile: ./ducdv-docker/admin-console/Dockerfile
    container_name: ducdv-nro-admin-console
    #restart: on-failure:5
    restart: no
    ports:
      - "${NGINX_PORT:-8000}:8000"
    environment:
      NGINX_PORT: ${NGINX_PORT:-8000}
      API_HOST: ducdv-nro-admin-api
      API_PORT: ${API_SERVER_PORT:-8082}
    volumes:
      - ./ducdv-nro-admin-console/dist:/usr/share/nginx/html
      - ./ducdv-docker/admin-console/nginx.conf:/etc/nginx/nginx.conf.template
      - logs_data:/var/log/nginx
    depends_on:
      - admin-console-builder

volumes:
  mysql_data:
    driver: local
  logs_data:
    driver: local
    driver_opts:
      type: none
      device: ${OUTPUT_LOGS_LOCAL:-/home/user/docker-logs}
      o: bind

networks:
  app_network:
    driver: bridge
